server:
  port: 3366

eureka:
  client:
    register-with-eureka: true # 是否注册进 eureka 服务注册中心
    fetch-registry: true # 是否从 eureka 服务注册中心抓取已有的注册信息
    service-url:
      defaultZone: ${eureka.client.service-url.defaultZone} # 使用 Config 配置中心统一管理服务注册中心地址
