server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      # TODO: 自定义，consul 地址
      host: 192.168.190.134
      port: 8500
      discovery:
        service-name: ${spring.application.name}
