server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.190.134:8080 # TODO: 配置 Sentinel 控制台地址及端口号
        port: 8719 # Sentinel 控制台和客户端通信的端口号，不配置的话默认是 8719，如果被占用了会自动往上加 1 找一个未被占用的端口
        client-ip: 192.168.1.137 # TODO: 配置 Sentinel 客户端 IP（也就是本机 IP），不配置可能会识别成 Sentinel 控制台所在的 IP，导致错误
      web-context-unify: false # 开启 STRATEGY_CHAIN 链路流控模式，详见 issue #1213
      datasource:
        myFlowRule1: # 自定义数据源名称，任意
          nacos:
            server-addr: 192.168.190.134:8848 # TODO: Nacos Server 地址，多个可以用逗号隔开，这里我配置了 Nginx，所以这里写的是 Nginx 的地址
            namespace: myCustomNamespaceID # 命名空间 namespace ID，读取此 namespace 下的配置
            group-id: CUSTOM_GROUP # 组名
            data-id: ${spring.application.name}-flow-rules # 指定配置文件名
            data-type: json # 指定配置文件类型
            rule-type: flow # 指定规则类型，在 com.alibaba.cloud.sentinel.datasource.RuleType 中查看支持的类型

management:
  endpoints:
    web:
      exposure:
        include: '*' # 暴露所有端点，否则 Sentinel 控制台无法监控到 /actuator/sentinel 端点
