server:
  port: 8001

spring:
  application:
    name: cloud-payment-service # Eureka Server 中的展示的服务别名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 6.x 在 com.mysql.cj.jdbc 包下
    driver-class-name: com.mysql.jdbc.Driver
    # TODO: 自定义
    url: jdbc:mysql://192.168.190.134:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: W110514

mybatis:
  mapper-locations: classpath:mapper/*.xml
  # TODO: 自定义
  type-aliases-package: com.atguigu.springcloud.entities

eureka:
  client:
    register-with-eureka: true # 是否注册进 eureka 服务注册中心
    fetch-registry: true # 是否从 eureka 服务注册中心抓取已有的注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
