server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    # TODO: 自定义
    url: jdbc:mysql://192.168.190.134:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: W110514

mybatis:
  mapper-locations: classpath:mapper/*.xml
  # TODO: 自定义
  type-aliases-package: com.atguigu.springcloud.entities
