server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      default-filters: # 默认过滤器
        - SetRequestHeader=X-Request-Red, Blue # 设置请求头
      routes:
        # http://localhost:9527/payment/lb?open=false
        - id: payment_routh # 路由的id，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001 # 目标服务地址
          predicates:
            - Path=/payment/lb # 路径相匹配的断言条件
            - Query=open,false # 参数相匹配的断言条件，参数名为open，值为false

        # http://localhost:9527/payment/lb
        - id: payment_routh2
          uri: lb://CLOUD-PAYMENT-SERVICE # lb://服务注册中心的微服务名称，这种方式开启负载均衡
          predicates:
            - Path=/payment/lb # 路径相匹配的断言条件
            - Cookie=name,[a-z]+
            - Cookie=value,[a-z]+
            - Header=GatewayNeed, \d+
            - Host=localhost:9527
            - Method=GET
            - Query=id,.+ # 匹配任意请求参数
          filters:
            - SetStatus=401 # 设置响应状态码
            - MyPartialFilter # 自定义过滤器：只有当请求中携带了 user-id 头部信息时，才能访问

        # http://localhost:9527/payment/timeout
        - id: payment_routh3
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: Hystrix # 开启熔断
              args:
                name: fallbackcmd # 熔断后执行的命令
                fallbackUri: forward:/payment/fallback # 熔断后转发到的地址，必须能匹配 Path 断言

hystrix:
  command:
    fallbackcmd: # 熔断后执行的命令
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000 #服务超时时间

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

