server:
  port: 2004

spring:
  application:
    name: seata-order-saga-service
  cloud:
    alibaba:
      seata:
        tx-service-group: seata_test_tx_group # TODO：连接到指定事务分组，对应 service.vgroupMapping.default_tx_group 中的 default_tx_group 名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.190.134:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false # TODO: 自定义 MySQL 地址
    username: root
    password: W110514

mybatis:
  mapper-locations: classpath:mapper/*.xml
  # TODO: 自定义
  type-aliases-package: com.atguigu.springcloud.entities

feign:
  hystrix:
    enabled: false

seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.190.134:8848
      group: SEATA_GROUP
      namespace: seata
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      server-addr: 192.168.190.134:8848
      group: SEATA_GROUP
      namespace: seata
      username: nacos
      password: nacos
      data-id: seataServer.properties
