server:
  port: 80

eureka:
  client:
    # 不注册进eureka服务中心，不需要 @EnableEurekaClient
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

feign:
  # 设置
  client:
    config:
      default:
        # Feign 调用连接超时时间
        read-timeout: 5000
        # Feign 调用请求超时时间
        connect-timeout: 5000
  # 开启 feign.hystrix.enable，使 fallback 生效
  hystrix:
    enabled: true

# 开启 feign.hystrix.enable，使 fallback 生效，但是会使 read-timeout 和 connect-timeout 失效，需要在使用以下配置
hystrix:
  command:
    default: # default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true # 如果enabled设置为false，则请求超时交给ribbon控制；为true，则超时作为熔断根据
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # 断路器超时时间，默认10000ms
            # timeoutInMilliseconds: 1000 # 测试 fallback 时，设置为 1s

logging:
  level:
    # 为指定的 @FeignClient 配置日志
    com.atguigu.springcloud.service.PaymentFeignServiceConfigurationTest: DEBUG
